- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIdIv7GOcQYhWohSxwck9zBsOHZViBudFIcf/noOyL0O0p3B6aWUyFMrpjmqotxkjpF0Sjxzx14vfLsYXYsqN63PTH4ilgl6vQ4sS7gkZvDTQgWEGy3hiax6EE2CCByoEG0r293nejgOKttSB3osATtGypJm2rWRW+3cWH6tkJHB8b52QdUvJ26tA+yO2hBUMqoXun5k9HskcIb/lHLUXgL1KEXsDQnYBHTZv4a4qDSPx2hZch2896FNXZCrIxl3DunaPCB47FWsWQs+IVc0CqmBLwG4DYgWJ/x4VfUsPG+ikvoNXGE3l5duEDoW3GhBkCxrCLFe+ofKE8s9nOAZkaoabfliv8XRBA0vMipr4zJ5fGISZRx3RH6vScTDEuVmDGCJ2TSz4y7DSzyD4JIpwGgOTstyj+D/yOKhGl6tP/C84EuALGnRG/rD8nsWKnnyE1Jz4BuNrZ/JicKgWpkbza2u2YfFX/veh7w7H94Z5aBTzz8dsI/aE99cQnXz1HG6E= johngranahan@pop-os"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
